### ISSUE TITLE
MBB pbp data not pulling latest

### ISSUE THREAD

**Issue by wparry22** [saiemgilani/sportsdataverse-py#16]
![image](https://user-images.githubusercontent.com/15950797/154738132-56f2c2df-ec33-41b1-9060-32726677479c.png)

**Comment by saiemgilani** [comment]
Probably because it isn't stored as a date. Will make a note to change that/simplify it

**Comment by saiemgilani** [comment]
Super weird. I did nothing. There must be something getting overwritten badly at some point in time

**Comment by wparry22** [comment]
Schedule is only through 1/8 this time FYI:

![image](https://user-images.githubusercontent.com/15950797/155821558-38f104a1-9789-428e-9c34-c7427c268ca9.png)
