### ISSUE TITLE
MBB Update Schedule

### ISSUE THREAD

**Issue by wparry22** [saiemgilani/sportsdataverse-py#4]
How often is MBB updated?

![image](https://user-images.githubusercontent.com/15950797/142302775-c0df2407-df2e-4dc1-8726-f2577befce11.png)

**Comment by saiemgilani** [comment]
It should be every day but I'm having some troubles with the data not pushing or running as often as it should. I see what you're saying.

**Comment by wparry22** [comment]
Alright, thanks!
